### ISSUE TITLE
Atgriezt norādi par neviennozīmīgām vārdšķirām

### ISSUE THREAD

**Issue by PeterisP** [LUMII-AILab/Webservices#1]
@lauma saka, ka divdabjiem u.c. vajadzētu tēzaurā rādīt, ka tie ir divdabji nevis īpašības vārdi.

tēzaurā šādiem vārdiem ir karodziņš "Citi": "Neviennozīmīga vārdšķira vai kategorija" 

pieprasījums https://api.tezaurs.lv/v1/inflections/apd%C4%81vin%C4%81ts?paradigm=13 varētu atgriezt arī šo karodziņu, lai tēzaurs var pareizi noformēt rezultātus.

**Comment by lauma** [comment]
Prioritāšu secība:
(1) Ja Tēzaurā rakstīts, ka problēma ar vārdšķiru/kategoriju, nerādīt vārdšķiru vispār
(2) Ja Tēzaurā ir norādīta kategorija, bet nav rakstīts, ka būtu problēma, rādīt kategoriju no Tēzaura
(3) Ja Tēzaurā ir paradigma, bet nav nekā no augstāk minētā, tad laikam var rādīt to vārdšķiru, kas sanāk noklusētā paradigmai

**Comment by PeterisP** [comment]
Pēc pēdējā gada Tēzaura paradigmu sakārtošanas šis laikam nav aktuāls, divdabjiem arī ir savas paradigmas tagad

**Comment by lauma** [comment]
Jā, šis ir novecojis, Laura ir visu tur sakārtojusi, izņemot varbūt pāris dīvaiņus, no kuriem sāp galva visiem.
