### ISSUE TITLE
Korpusa piemēru serviss - neiekļaut zinātniskos

### ISSUE THREAD

**Issue by normundsg** [LUMII-AILab/Webservices#2]
Tēzauram atlasītajos korpusa piemēros nevajag iekļaut piemērus no zinātniskajiem tekstiem - tie ir pārāk sarežģīti un nereti arī negramatiski.

Ja nu vienīgi gadījumos, kad nav citu žanru piemēri.

**Comment by PeterisP** [comment]
Pēc parunāšanās ar valodniekiem nav viennozīmīgi, un risinās ar jaunieviesto sistēmu sliktu piemēru blacklistošanai un arī ar redaktora iespēju manuāli norādīt piemērus.
