### ISSUE TITLE
Tēzauram 6diena - viena tekstvienība

### ISSUE THREAD

**Issue by lauma** [LUMII-AILab/Webservices#6]
Tēzaurs grib tokenam `6diena` likt 4. deklinācijas lietvārda paradigmu, šobrīd https://darbaversija.tezaurs.lv/6diena neveido tabulu, jo analizatora serviss uzskata, ka tas jādala 2 tokenos - `6` un `diena`, bet valodnieku mērķis ir locīt kā vienu tokenu.

**Comment by PeterisP** [comment]
Salabots ar jaunākajām morfoloģijas izmaiņām
