### ISSUE TITLE
satura tips JSON datiem

### ISSUE THREAD

**Issue by mikusg** [LUMII-AILab/Webservices#7]
Būtu noderīgi, ja tur, kur atbildes dati ir JSON, tiem atbildes galvenē būtu arī rinda ar datu tipu, apmēram 
`"Content-Type": "application/json"`.

Tur, kur datus patērē cita lietotne, tur tas īsti neko nemaina, bet tad, ja datus izgūst tieši no pārlūka (piemēram, no skaņošanas restītes T darba versijās), tad skaidri pateikts datu tips varētu būt palīdzīgs, lai datus uzreiz glītāk noformatētu.

Šobrīd atbildes tips, šķiet, ir `text/plain`.

**Comment by lauma** [comment]
Runa ir par, piemēram, https://api.tezaurs.lv/v1/inflections/es?paradigm=pron&inflmisc=Vienskaitlis vai https://api.tezaurs.lv/v1/inflections/aukl%C4%93t?paradigm=verb-2-ltg
